# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_auto_20180603_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=100)),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
