# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-26 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='commentNum',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='article',
            name='viewNum',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
