# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-27 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_auto_20180526_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='commentNum',
        ),
    ]
