# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-27 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_article_commentnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='commentNum',
            new_name='commtentNum',
        ),
    ]
